In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df = pd.read_csv('data2010-2011s1.csv', encoding = "ISO-8859-1")  #on a 8 colonnes
df.head  #permet de voir les première lignes du data set

<bound method NDFrame.head of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
245898    558637     22032         BOTANICAL LILY GREETING CARD        12
245899    558637     22028         PENNY FARTHING BIRTHDAY CARD        12
245900    558637     22033         BOTANICAL ROSE GREETING CARD        12
245901    558637     22029               SPACEBOY BIRTHDAY CARD        12
245902    558637     22024           RAINY LADIES BIRTHDAY CARD        12

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
245898  6/30/2011 20:08       0.42     17891.0  United Kingdom
245899  6/30/2011 20:08       0.42     17891.0  United Kingdom
245900  6/30/2011 20:08       0.42     17891.0  United Kingdom
245901  6/30/2011 20:08       0.42     17891.0  United Kingdom
245902  6/30/2011 20:08       0.42     17891.0  United Kingdom

[245903 rows x 8 columns]>

In [5]:
dfproduit = df[['StockCode','Description' , 'UnitPrice' ]].copy()  #pour suppriemr les doublons entre les 3 colonnes de num produit
#description et prix unitaire
dfproduit.drop_duplicates(inplace=True)
dfproduit

       StockCode                          Description  UnitPrice
0         85123A   WHITE HANGING HEART T-LIGHT HOLDER       2.55
1          71053                  WHITE METAL LANTERN       3.39
2         84406B       CREAM CUPID HEARTS COAT HANGER       2.75
3         84029G  KNITTED UNION FLAG HOT WATER BOTTLE       3.39
4         84029E       RED WOOLLY HOTTIE WHITE HEART.       3.39
...          ...                                  ...        ...
245898     22032         BOTANICAL LILY GREETING CARD       0.42
245899     22028         PENNY FARTHING BIRTHDAY CARD       0.42
245900     22033         BOTANICAL ROSE GREETING CARD       0.42
245901     22029               SPACEBOY BIRTHDAY CARD       0.42
245902     22024           RAINY LADIES BIRTHDAY CARD       0.42

[245903 rows x 3 columns]